### PR TITLE
multi: bump btcec/v2 and btcutil to new versions

### PR DESCRIPTION
**Pull request by guggero**
Bumps all dependencies to be compatible with the `btcec/v2` and new `btcutil` submodules.

Depends on https://github.com/lightninglabs/lndclient/pull/96.

### CODE REVIEW

**Comment by bhandras** [comment]
Looks like the linter got over excited..

**Review by bhandras — APPROVED** [review]
LGTM :taco:

**Comment by guggero** [comment]
Thanks, fixed the linter issue.

**Review by positiveblue — APPROVED** [review]

**Review by carlaKC — APPROVED** [review]
Assuming the build failure is unrelated? I remeber there was some issue with it.

**Comment by guggero** [comment]
Yes, the build failures are unrelated. I confirmed it's "only" https://github.com/lightninglabs/aperture/issues/71 and no new failure.

**Pull request merged**
