### PR TITLE
unit-race: fix race condition in unit tests

### PR DESCRIPTION
**Pull request by guggero**
Fixes https://github.com/lightninglabs/aperture/issues/71.

Turns out the problem was the histogram metrics for Prometheus added recently. They [aren't concurrency safe](https://github.com/grpc-ecosystem/go-grpc-prometheus/pull/110). Since we don't start multiple instances of Aperture _within the same process_ in production, we should never hit that outside of race unit tests.

We also move over to GitHub Actions because Travis sucks.

### CODE REVIEW

**Comment by guggero** [comment]
Okay, weird, the one race condition is still there. Didn't happen locally with `go 1.16.3` but happens on GitHub with `go 1.17.8`. Trying out a few things.

**Comment by guggero** [comment]
Yayy, I was able to fix the tests by pinning everything to `go 1.18.9` :tada:

**Review by ellemouton — APPROVED** [review]
Amazing!!! 🔥

**Review by positiveblue — APPROVED** [review]
Just of the travis migrations this PR deserves a big approve :tada: :tada: 

(I guess that you meant that you uploaded go to version `1.16.9` instead of `1.18.9` ?)

**Review by carlaKC — APPROVED** [review]

**Comment by guggero** [comment]
> Just of the travis migrations this PR deserves a big approve tada tada
> 
> (I guess that you meant that you uploaded go to version `1.16.9` instead of `1.18.9` ?)

Yeah, typo :) Fixed the comment. Thanks for the review!

**Pull request merged**
